### ISSUE TITLE
Korean Focus issues

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#118]
**Description**
"Large Vessel Plans" and "Small vessel Plans" have no effect. 
The big Korean focus has no name, maybe intended. 
"No negociation policy" is misspelled, should be "Negotiation". Also it has a broken effect.
"Southern Rice Cultivation" has no icon.
"End Mass starvation" has no effect.
"Deforestation" branch issues: (See screenshot)

**Branch**
[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)] 

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/165285186-4b0ea8fa-e9b6-4521-9132-4177a32e701c.png)
![image](https://user-images.githubusercontent.com/103889190/165285458-230ab6a6-d824-4262-843b-ff21cb2096f9.png)
![image](https://user-images.githubusercontent.com/103889190/165285769-4c7bb854-317d-44eb-8d09-12033bfe4b41.png)
![image](https://user-images.githubusercontent.com/103889190/165285924-060efd79-ec27-44ec-8c24-fab33ea9e02e.png)
![image](https://user-images.githubusercontent.com/103889190/165286586-f86f732d-b10c-4194-ab4e-579eda362eb8.png)

**Comment by Imperialism1** [comment]
Large Korean focus is not supposed to have a name, that is intentional. The effect of the no negotiation policy is meant to add a country flag which will increase the willingness of the Koreans to not surrender against whoever it is they were fighting at that time (I think Americans). Basically despite the American expedition making good grounds and even reaching the capital, the government just straight up went somewhere else and refused to negotiate with any Americans. That is why the Americans just ended up leaving in the end.

**Comment by Imperialism1** [comment]
Everything except for the mass starvation focus is fixed. The Agriculture/Right side in general of the tree was never reworked when I went through and was reworking parts of the content so I expect that sometime in the future all of that will be redone or at least partially reworked.
