### ISSUE TITLE
U.S. Campaign

### ISSUE THREAD

**Issue by Docwhatshisface** [team-eoanb/EoaNB#39]
(Edited for clarity, er, kinda.)

I think (hope!) that this is where a thread like this is supposed to go. I've never bothered putting together a report like this for a mod as I usually either fix or work-around an issue myself, or wait for it to be fixed. However, I am so impressed by EoaNB that about three weeks ago I decided to start doing some 'play tests' in order to attempt to attempt-to replicate and then document the bigger issues I've found.

Now, after being completely disappointed, even angry, at La Resistance's release I put down HoI4 in favor of some other games I own; this newest DLC struck me as nothing more than a shameless cash grab, indeed, even a poorly copied and thought-out knock off of the Espionage mod. Yet, as often happens, it wasn't too many weeks before I felt the itch again and thus returned to the game. However, this time I did some new mod hunting to see if anything good had popped up. Before La Resistance, I'd been playing with the Great War mod, and before that Millennium Dawn, but now I wanted something different. Lo and behold, I saw End of a New Beginning and was instantly intrigued as I recognized the Churchill quote (you see, I too am a man of culture)! I started up the U.S. campaign, and now in 1933 all I can say is: Hearts of Iron 4 is back... and with a vengeance! Long and short, I absolutely love what you all are doing with this mod. In fact, I think this has the potential to be the (definite article!) must-have mod for this game. Thank you all for the amazing efforts thus far! I'm quite eager to see how this mod develops over the new few months.

Now, all that said, I've been running into some issues over the past few weeks. In fact, by about 1880 in my first campaign I thought that perhaps I had broken something. So, I went back with a clean reinstall of both the game and EoaNB to try again; however, this time I was prepared to play test and to write down issues as I recognized them. So, while a couple issues disappeared with the reinstall (specifically, a few minor graphical issues, probably from my own tinkering with game files) here are the bigger things which have either persisted and/or I've noticed in this second play through. Again, at the time of writing, I'm at 1933 and playing as U.S. in my "main" campaign; I've also conducted four additional 'play tests,' each of them also at 1933. Now, I've limited the list only to those "bigger" problems. Because I've never created a report like this, I didn't know how helpful listing "minor" bugs would be. Finally, any issue which I could not reproduce in 'test plays' I simply deleted from my list. 

Nota bene: my over-riding assumption with all of these problems is that the content is simply incomplete--y'know, alpha stage and all. That is to say, it is by no means a reflection of what I think of this mod as a whole. So, here we go:

--First, many of the "Admit States into the Union" "Decisions" simply do not work despite meeting the requirements. Either the option is never available or when it is available and clicked-on nothing happens; indeed, some of them even can be activated more than once yet still do not work. Thus far, the only state to work and stay-working has been Minnesota--the rest are still split up according to the previous state borders of the now-conquered Native American tribes (Crow, Apache, etc.). 

--Next, despite having recently passed into the "Age of Flight," the focus tree is still stuck in "The Gilded Age." In my third and fourth 'test plays' I used the console commands in order to ignore the requirements and complete all of the focuses. Yet, to date, the FT remains in "The Gilded Age."

--Related to the above, I think, are numerous Civil War and Reconstruction eras' National Spirits and Decisions which are still active.
          NS: "Aggressive Assault," "The Anaconda Plan," "Revenue Act of 1861," and "Freedman's Bureau."
          Decisions: "Patrol the Streets." (In about 1890, the other three anti-KKK decisions simply disappeared in both the main campaign as well as play tests!)

--After these, the Statue of Liberty has seemingly never been built. Hence, choosing the National Focus "American Dream" is impossible without console commands. Even with these activated and the FT branch completed there is still no indication that it was ever built.

--Additionally, although the USS Maine explodes and the option to blame Spain is chosen, the Spanish-American war never occurs. Instead, after "Big Stick Diplomacy" is complete the FT refuses to advance without console commands; even with these commands entered in the third and fourth play test the war simply doesn't occur. Now, in the second and fourth 'test plays' (2nd, no console command for the related FTs and 4th, console command for the related FTs), despite declaring war on Spain manually, the Spanish-American war never happened, nor did fighting Spain (winning in 2nd, losing intentionally in 4th) fix any of the above.

--Next, the "Rush for Africa" still hasn't happened. As such, the colonial research branch is stuck. In both the third and fourth test plays, I used the console command in order to force the research to happen--yet, nothing doing. In the third test play I established a handful of random colonies in Africa but this didn't cause the colonization rush to happen. Likewise, in the fourth I picked some different colony locations and even started wars with France and Spain in order to take away the colonies they start the game with, but again no rush into the Dark Continent. Rather, in all instances Africa remains a giant bundle of Tribal countries.

--Also, WWI never occurred in any play through. I was tempted to use console commands to attempt to manually create the "main" two factions and get them warring in 1914 but I haven't done so for fear that it might make void my test play results.

--Oh, interestingly, each play through has given me the notification, in about 1918: "Invalid Idea Mechanical Engineer Corps." The reason stated is: "...removed because its prerequisites are no longer fulfilled." I have no idea what this means as there have been no decisions, focus tree, research options, or national spirits about this, neither any prior notifications.

--After this, the Panama Canal never works. That is to say, all ships must sail around the southern tip of S. America. In the third play test I specifically went to war with the Kingdom of Columbia to seize Panama but the canal remained broken; in the fourth, I seized all of central America as well as Columbia with the same result--no research, decision, or focus tree to get that stupid canal operational.

--Next, despite unlocking the relevant research ("GMC CCKW," et al.) most "Support Companies" are still not-themselves mechanized (or even horse-drawn!). As such, with the singular exception of "Signal," adding any support company to any non 'leg-infantry' unit (i.e. cavalry, armored car, mechanized infantry, etc.) causes the division's speed to drop to 4. This issue, though quite annoying I must admit, is nonetheless a bit funny--as if the binoculars, compass, and maps used by "recon" attachments are so big and/or fragile that they cannot be carried in saddle bags or in the bed of the "GMC CCKW!" Lol!!

--In addition, many research items have incredibly long periods to unlock them, even when I'm at or even beyond the required year. I'm not sure if this is a bug or a feature, but the aircraft technology is especially bad; for example, in the 3rd and 4th play tests, unlocking the Wright Brothers' plane in 1910 required over 1,000 days' research.

--Now, this one's more of an annoyance than anything else, but the sheer amount of "World Fairs" is mind-boggling. In every playthrough after about 1880 there's at least one a month but most-often two or three per month! Shoot, in one case, right after manually going to war with Spain, I counted six - SIX - World Fairs! LMAO! I guess the rest of the planet was so desperate for peace that they were trying to distract me and Spain!

--Next-to-last, all of these playthroughs have have been the (definite article) most peaceful I have ever seen in HOI4. Aside from infrequent skirmishes between African tribal states, and tiny wars in China hardly any one goes to war, especially the major powers. Without putting it too harshly, this causes the game to be, well, pretty boring. In the first couple of decades there seems to be a "normal" amount of fighting but this gradually tapers off to almost nothing by 1900.

--Finally, and I think related to the above, or perhaps a separate bug, in the fourth play test I used the 'allowdiplo' command to start fights with numerous countries in order to annex their lands (and relieve my boredom!) and to trigger containment (a feature that I simultaneously absolutely hate yet completely adore in Vic2). Yet, when the world decided to attempt to contain my burgeoning empire their forces were so pathetic that I utterly smashed them--while also fighting ALL of South America, mind you--without breaking a sweat; the German Federation for example, the #2 major power at the time, had no more than 61 divisions while I had a little under 300.

In conclusion, despite the problems I've listed I think that EoaNB is absolutely brilliant! I've truly never seen a mod for a Paradox game that is so ambitious yet thoughtfully planned out--as if you all were channeling Darth Mod's spirit! Between what I've seen in-game and what little I can tell from scanning the files, I am very excited to continue to play and follow the progress of this mod; the ideas that you all have-already or are still-implementing are breathing new life into what is an otherwise unworthy successor of HoI3. In fact, I suspect that in a few months this mod will make HoI4 as-good if not better than its predecessor ever was! 

I hope this is helpful to you all. If it is, please let me know and I'll continue to update this or if you'd prefer, I can play test other countries in a similar manner. Nevertheless, from the bottom of my heart, thank you, Thank You, THANK YOU!!

**Comment by Vanadium-GITHUB** [comment]
Hi, I'm Vanadium, a developer for the United States. First of, I'd like to say thank you for playing our mod and taking the time on compiling all of this together. We take all user feedback, and as the mod is still in Alpha, there are sure to be a lot of incomplete content or features/mechanics that might not work fully as intended. It really helps to make sure we know what is working and what isn't so we can keep out 2do lists up to date!!

So, before I respond to the nitty gritty, I would like to ask which GitHub branch you are using, or if you are using Steam. It's not too obvious, maybe we should change the documentation, but both the Steam version and the master branch are outdated by two or so months, and a some features, like State admission and the scramble for Africa might work better in newer versions. The latest version should be our experimental branch. If you haven't yet, try it out!

Addressing a few related issues relating to mid-game content: Recently (well, months ago, but it still feels recent), the modding team went through a lot of restructuring and rehauling of how we want things to accomplish. With our new philosophy, we are trying to focus our attention and time on developing more *quality* and *indepth* content in specific time frames, and don't work on the next timeframe until we are happy with what we have so far. Our current timeframe of development is the first 25 years, 1857-1882 and we justify this because the content in the Beginning of campaigns are always met with the most user interaction and slowly drop after as, well, people like starting new campaigns. Because of the change in approach, progress on mid-game content, like your mentioned Age of Flight focus tree, Spanish American War, Scramble for Africa have been left on the backburner until we are happy with the first 25 years.

Because of those reasons, I'd like to ask you and anyone else that might be reading this to please be patient with us while we catch up in development! :sweat_smile: 

As for the Civil War and Reconstruction National Spirits, yea, I gotta go through and change them all to timed ideas. Previous American dev, President Storm, forgot to make them so :p I'll look into it soon! KKK and the American Dream, Panama Canal, reference the above paragraph.

Addressing the Scramble for Africa in detail, the Scramble of Africa is locked behind the attending the Berlin Conference. You can only attend if you are invited, and currently, as far as I'm aware we only have plans for select European majors to be be able to attend. (ex. france, britain, germany, etc). So you, as the US, being blocked from being able to research that technology is 100% intentional. While the AI needs to be worked on, so it can itself be smart on using colonialization, I'm pretty sure if you are playing a european country intended to have colonialism, it should work properly in a similar manner to Vic2.

I'm not 100% familiar with our philosophy on technology, balance on technology, but I assume techs like researching the plane are intended on being huge investments, and if one really wants to stay on pace with air research, the devote a lot of political will to get air research discounts (which was planned but, well, was never gotten around to before change in attention). The support slowing down units sounds fraught, I will bring this to our tech lead's attention. Finally I assume what we hoped to have, was the national concerns, like Mechanical Engineer Corps, would become outdated with time and you would have to reinvest political power on getting a new company to help you with research. (again, unfinished)

Finally, to address to boredom of a world without wars, well, all I can say is there is a huge rehaul in how wars, imperialism, and conquest are portrayed in the game so that it will feel more dynamic and interesting without letting countries simply blob hoi4 style. Because if you've ever played hoi4, countries in that game blob real quick if we let them declare full wars by themselves, which doesn't exactly bode well for a mod intended to last a few centuries haha.

Hope this response helps! I know a lot of my answers are not exactly fulfilling, but honesty is better than vague promises we can't actually achieve. 😄 If you have anymore questions join the discord: https://discord.gg/gXgDfTF
- Vanadium

**Comment by Docwhatshisface** [comment]
Thank you for the prompt response! Oh, shoot, I never did say the version--my bad; it's the 1.9.3 update. 

"I know a lot of my answers are not exactly fulfilling, but honesty is better than vague promises . . ." 
Nah, no worries, I myself prefer honesty. Basically, it seems that I need to put down the American campaign for now and pick up other countries. Furthermore, nothing you've said is illogical given the goals you've described; for example, preventing blobbing, and America not being invited to the Berlin Conference are completely reasonable. Ha! I guess it's time to fire up some other countries then. 

I appreciate the discord invite but I gotta decline. Given my IRL obligations I must be fairly strict with how I spend my time otherwise I'll have none for gaming. As such, for myself, the best way for me to 'save time' is by avoiding social media/discord/et al. 😄 

Thanks again.

-Bill
