### ISSUE TITLE
Technological Eras

### ISSUE THREAD

**Issue by ZdravkoWare** [team-eoanb/EoaNB#42]
I noticed that when upgrading through the ages, the research speed goes down. And it seems very weird. Is this intentional?

**Comment by Vanadium-GITHUB** [comment]
Hello zdravko, I'd like to let you know that this is fully intentional!

The way it works, as you go to the next age, the technologies you need to research continue to become more complex and hard to research. We simulate that by making the countries struggle to research these when they enter the era by slapping that research penalty onto them. It is part of the balance that as the game progresses, countries will continue to unlock bonuses to research speed. This is to make the player/AI always want to continue researching the science techs and look for research bonuses, as well as deter countries from rushing eras!

Hope this helps!
